export const products = [
  {
    id: 1,
    title: "HTML & CSS",
    price: 150,
    stock: 0,
    description: "Learn HTML & CSS",
    category: "frontend",
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1681325472/html_css_fcykdf.png",
    contains: ["HTML", "CSS", "Git and Github", "SASS", "Bootstrap", "Node"],
  },
  {
    id: 2,
    title: "JavaScript",
    price: 300,
    stock: 4,
    description: "Learn JavaScript",
    category: "frontend",
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1681325732/javascript_zvrrf3.png",
    contains: [
      "Basics",
      "Events",
      "Objects",
      "Storage & JSON",
      "Fetch",
      "Frameworks",
    ],
  },
  {
    id: 3,
    title: "ReactJS",
    price: 350,
    stock: 3,
    description: "Learn ReactJS",
    category: "frontend",
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1681325731/react_w7b7ry.png",
    contains: [
      "Basics",
      "JSX & Transpiling",
      "Components",
      "Context",
      "Routing",
      "Rendering",
    ],
  },
  {
    id: 4,
    title: "jQuery",
    price: 300,
    stock: 3,
    description: "Learn jQuery",
    category: "backend",
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1681936115/jquery_vkiwnm.png",
    contains: [
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
    ],
  },
  {
    id: 5,
    title: "MySQL",
    price: 300,
    stock: 0,
    description: "Learn MySQL",
    category: "backend",
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1681936115/mysql_nxizu3.png",
    contains: [
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
    ],
  },
  {
    id: 6,
    title: "AWS",
    price: 300,
    stock: 1,
    description: "Learn AWS",
    category: "backend",
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1681936115/aws_zlqroh.png",
    contains: [
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
      "Placeholder",
    ],
  },
];
